[package]
name = "netwatcher"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_vendor = "apple")'.dependencies]
nix = { version = "0.29.0", features = ["net"] }
block2 = "0.5.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.56.0"
features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
]
