[package]
name = "netwatcher"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["net"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.56.0"
features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
]
