name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Android Rust targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android
    
    - name: Build app containing Rust NDK component
      working-directory: ./android
      run: sh ./gradlew assembleDebug
    
    - name: Run clippy
      run: cargo clippy --target aarch64-linux-android --all-targets -- -D warnings
    
    - name: Run clippy on Android example code
      working-directory: ./android/app-native
      run: cargo clippy --target aarch64-linux-android --all-targets -- -D warnings
    
    - name: Check formatting of Android example code
      working-directory: ./android/app-native
      run: cargo fmt --all -- --check
